chainid: "999999999"
network: zora-sepolia
factories1155:
  - address: "0x777777C338d93e2C7adf08D102d45CA7CC4Ed021"
    startBlock: "309965"
    version: "1"
factories721:
  - address: "0x6b28d7C2F8b2C2189e95b89B67886eEb16489a97"
    startBlock: "307400"
    version: "1"
protocolRewards:
  - address: "0x7777777F279eba3d3Ad8F4E708545291A6fDBA8B"
    startBlock: "2384107"
    version: "2"
preminter:
  - address: "0x7777773606e7e46C8Ba8B98C08f5cD218e31d340"
    startBlock: "309965"
    version: "1"
reserveAuctionV3:
  - address: "0x0fbAB7302F9351dD1DB6674cc3bB855f0C55840B"
    startBlock: "992417"
    version: "1"
zoraMints:
  - address: "0x7777777d57c1C6e472fa379b7b3B6c6ba3835073"
    startBlock: "7129497"
    version: "1"
mintsManager:
  - address: "0x77777770ca269366c7208afcf36fe2c6f7f7608b"
    startBlock: "7129497"
    version: "1"
erc20Minter:
  - address: "0x777777E8850d8D6d98De2B5f64fae401F96eFF31"
    startBlock: "6695930"
    version: "1"
