[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'script']
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 5000
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config