chainid: "999"
network: zora-testnet
factories1155:
  - address: "0x6a357139C1bcDcf0B3AB9bC447932dDdcb956703"
    startBlock: "1"
    version: "1"
  - address: "0x777777C338d93e2C7adf08D102d45CA7CC4Ed021"
    startBlock: "1278602"
    version: "2"
factories721:
  - address: "0x1Fc0BAE875C2CF2262BEc25B16d96814D37025AC"
    startBlock: "1"
    version: "1"
  - address: "0xeB29A4e5b84fef428c072debA2444e93c080CE87"
    startBlock: "587491"
    version: "2"
protocolRewards:
  - address: "0x7777777A456fF23D9b6851184472c08FBDa73e32"
    startBlock: "780419"
    version: "1"
  - address: "0x7777777F279eba3d3Ad8F4E708545291A6fDBA8B"
    startBlock: "823043"
    version: "2"
preminter:
  - address: "0x7777773606e7e46C8Ba8B98C08f5cD218e31d340"
    startBlock: "1278602"
    version: "1"
