on:
  workflow_call:
    inputs:
      package_folder:
        required: true
        type: string
      name:
        required: true
        type: string
      precache:
        required: false
        type: string

jobs:
  check:
    strategy:
      fail-fast: true

    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set initial test ${{ inputs.name }} status
        uses: myrotvorets/set-commit-status-action@968047d472cada5abe7920db2b2e539e54e4610e # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Test ${{ inputs.name }} status

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Run precache command
        if: ${{ inputs.precache != null }}
        run: cd ${{ inputs.package_folder}} && ${{ inputs.precache }}

      - name: Load foundry cache
        if: ${{ !contains(github.event.head_commit.message, format('skip-cache-{0}', inputs.package_folder)) }}
        uses: ./.github/actions/cache_foundry_build
        with:
          package_folder: ${{ inputs.package_folder }}

      - name: Build contracts
        run: |
          cd ${{ inputs.package_folder}} && forge build

      - name: Test
        run: |
          cd ${{ inputs.package_folder}} && pnpm run test
        env:
          TENDERLY_KEY: ${{ secrets.TENDERLY_KEY }}
          CONDUIT_KEY: ${{ secrets.CONDUIT_KEY }}

      - name: Set initial test ${{ inputs.name }} status
        uses: myrotvorets/set-commit-status-action@968047d472cada5abe7920db2b2e539e54e4610e # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Test ${{ inputs.name }} status
